title: Horizon News
description: Latest news and updates across tech, sports, Bollywood, and more.
baseurl: "/sp"
url: "https://horizon025.github.io"
permalink: /:categories/:title/

theme: jekyll-theme-primer
source: .
destination: ./_site
markdown: kramdown
future: true
exclude: [vendor, .github, README.md]

plugins:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-relative-links

github:
    is_project_page: true

paginate: 5
paginate_path: "/sp/page:num/"

seo:
    type: Website

primer:
    syntax_highlighter: rouge

defaults:
    - scope:
        path: ""
        type: posts
      values:
        layout: post
        published: true
